language: ruby

cache: bundler

branches:
  only:
  - master

before_script:
  - gem install bundler jekyll
  - bundler install 
  - sudo apt update && sudo apt install jpegoptim

script:
  - ./scripts/resize.bash
  - bundler exec jekyll build
  - echo "occhietticuriosi.it" > _site/CNAME
  
deploy:
  provider: pages
  local_dir: _site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
