language: ruby

branches:
  only:
  - master

before_script:
  - gem install bundler jekyll
  - bundler install

script:
  - ./scripts/resize.bash
  - bundler exec jekyll build
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
